messages:
  lock-success: "§bcontainer locked. Use §a/unlock§b to unlock it and §a/lock + <players>§b to add other players."
  lock-usage: "§a/lock §b[+/- <players>]"
  unlock-success: "§bcontainer unlocked."
  lock-add-success: "§a{NAME}§b can now use this container."
  lock-remove-success: "§a{NAME}§b can no longer use this container."
  error-look-at-container: "§cYou must look at a container to use this command."
  error-already-locked: "§cThis container is already locked."
  error-not-locked: "§cThis container isn't locked."
  error-not-owner: "§cThis container doesn't belong to you."
  error-already-has-access: "§6{NAME}§c can already use this container."
  error-already-has-no-access: "§6{NAME}§c cannot use this container."
  error-player-does-not-exist: "§cThe player §6{NAME}§c doesn't exist."
  container-locked: "§bThis container was locked by §a{NAME}§b."
  container-nearby-locked: "§cThe container next to this one is locked."

inventory-lockable: [
  "CHEST", 
  "TRAPPED_CHEST", 
  "BARREL", 
  "SHULKER_BOX"
]
  
